services:

  frontend:
    build: ./frontend
    container_name: support_ticket_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: .
    container_name: support_ticket_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/support_ticket_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    container_name: support_ticket_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_ticket_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d support_ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: